gfal-copy /data/jmao/LHE/m127_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m150_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m175_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m200_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m225_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m250_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m275_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m300_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m325_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m350_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m375_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m400_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m425_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m450_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m475_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m500_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m525_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m550_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m575_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m600_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m625_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m650_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m675_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m700_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m725_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m750_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m775_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m800_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m825_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m850_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m875_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m900_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m925_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m950_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m975_pl10000.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
