gfal-copy /data/jmao/LHE/m127_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m150_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m175_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m200_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m225_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m250_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m275_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m300_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m325_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m350_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m375_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m400_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m425_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m450_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m475_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m500_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m525_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m550_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m575_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m600_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m625_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m650_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m675_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m700_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m725_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m750_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m775_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m800_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m825_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m850_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m875_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m900_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m925_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m950_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
gfal-copy /data/jmao/LHE/m975_pl100.lhe gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/aodsim/RunIISummer16/LHE/MSSM-1d-prod/n3n2-n1-hbb-hbb/ 
